import React from 'react';

export const metadata = {
    title: {
        absolute: 'Meals'
    },
    description: 'Generated by create next app'
  }

const MealsPage = () => {
    return (
        <div>
            <div className='w-96 h-96 bg-white bg-opacity-10'>
                    <h1>hello</h1>
            </div>
        </div>
    );
};

export default MealsPage;